<option value="" class="text-muted">Pilih pekerjaan</option>
<option value="Tidak Bekerja">Tidak Bekerja</option>
<option value="Pedagang">Pedagang</option>
<option value="BUMN">BUMN</option>
<option value="Pensiunan">Pensiunan</option>
<option value="PNS selain (Guru dan Dokter/Bidan/Perawat)">PNS selain (Guru dan Dokter/Bidan/Perawat)</option>
<option value="PNS">PNS</option>
<option value="TNI/POLRI">TNI/POLRI</option>
<option value="Pegawai Swastar">Pegawai Swasta</option>
<option value="Wiraswasta">Wiraswasta</option>
<option value="Pengacara/Hakim/Jaksa/Notaris">Pengacara/Hakim/Jaksa/Notaris</option>
<option value="Seniman/Pelukis/Artis/Sejenis">Seniman/Pelukis/Artis/Sejenis</option>
<option value="Dokter/Bidan/Perawat">Dokter/Bidan/Perawat</option>
<option value="Pilot/Pramugara">Pilot/Pramugara</option>
<option value="Pedagang">Pedagang</option>
<option value="Petani/Peternak">Petani/Peternak</option>
<option value="Nelayan">Nelayan</option>
<option value="Buruh (Tani/Pabrik/Bangunan)">Buruh (Tani/Pabrik/Bangunan)</option>
<option value="Sopir/Masinis/Kondektur">Sopir/Masinis/Kondektur</option>
<option value="Politikus">Politikus</option>
<option value="Lainnya">Lainnya</option>